version: "3.7"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.13
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    container_name: jaeger

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "8080:15672"
    container_name: rabbitmq